name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8.0
#          cache: gradle
#
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build --stacktrace
#
#
#      - name: Run tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 26
#          script: ./gradlew connectedCheck --info --stacktrace
##         run: ./gradlew connectedAndroidTest --info



#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout
#         uses: actions/checkout@v3

#       - name: run tests
#         uses: reactivecircus/android-emulator-runner@v2
#         with:
#           api-level: 26
#           script: ./gradlew connectedCheck --info --stacktrace

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 26 ]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Local unit tests
        run: ./gradlew test --info --stacktrace

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck --info
